name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test on node ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install --global nyc
          yarn

      - name: Run lint, build and test-coverage
        run: |
          yarn lint
          yarn build
          yarn test-coverage

      - name: Upload coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
