name: Test

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        node:
          - 10.x
          - 12.x
        platform:
          - ubuntu-latest

    name: Test on node ${{ matrix.node }} and ${{ matrix.platform }}

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@master
        with:
          version: ${{ matrix.node }}

      - name: Install
        run: |
          npm install --global nyc
          yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: test-coverage

      - name: Upload Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
